server:
  port: 8083
spring:
  resources:
    static-locations:classpath:/static/
  # mysql
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 19990204
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    # thymeleaf
  thymeleaf:
      cache: false
      prefix: classpath:/templates/
      suffix: .html
      # mode: HTML5
      encoding: UTF-8
      servlet:
        content-type: text/html
# mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
